spring:
    datasource:
        url: jdbc:mysql://localhost:3306/iot?createDatabaseIfNotExist=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
    jpa:
        show-sql: true
server:
    port: 8081